// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserReq) Reset()         { *m = UserReq{} }
func (m *UserReq) String() string { return proto.CompactTextString(m) }
func (*UserReq) ProtoMessage()    {}
func (*UserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserReq.Unmarshal(m, b)
}
func (m *UserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserReq.Marshal(b, m, deterministic)
}
func (m *UserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserReq.Merge(m, src)
}
func (m *UserReq) XXX_Size() int {
	return xxx_messageInfo_UserReq.Size(m)
}
func (m *UserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UserReq proto.InternalMessageInfo

type UserResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResp) Reset()         { *m = UserResp{} }
func (m *UserResp) String() string { return proto.CompactTextString(m) }
func (*UserResp) ProtoMessage()    {}
func (*UserResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResp.Unmarshal(m, b)
}
func (m *UserResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResp.Marshal(b, m, deterministic)
}
func (m *UserResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResp.Merge(m, src)
}
func (m *UserResp) XXX_Size() int {
	return xxx_messageInfo_UserResp.Size(m)
}
func (m *UserResp) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResp.DiscardUnknown(m)
}

var xxx_messageInfo_UserResp proto.InternalMessageInfo

type StreamInputReq struct {
	Input                string   `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamInputReq) Reset()         { *m = StreamInputReq{} }
func (m *StreamInputReq) String() string { return proto.CompactTextString(m) }
func (*StreamInputReq) ProtoMessage()    {}
func (*StreamInputReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *StreamInputReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInputReq.Unmarshal(m, b)
}
func (m *StreamInputReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInputReq.Marshal(b, m, deterministic)
}
func (m *StreamInputReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInputReq.Merge(m, src)
}
func (m *StreamInputReq) XXX_Size() int {
	return xxx_messageInfo_StreamInputReq.Size(m)
}
func (m *StreamInputReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInputReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInputReq proto.InternalMessageInfo

func (m *StreamInputReq) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

type StreamInputResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamInputResp) Reset()         { *m = StreamInputResp{} }
func (m *StreamInputResp) String() string { return proto.CompactTextString(m) }
func (*StreamInputResp) ProtoMessage()    {}
func (*StreamInputResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *StreamInputResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamInputResp.Unmarshal(m, b)
}
func (m *StreamInputResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamInputResp.Marshal(b, m, deterministic)
}
func (m *StreamInputResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamInputResp.Merge(m, src)
}
func (m *StreamInputResp) XXX_Size() int {
	return xxx_messageInfo_StreamInputResp.Size(m)
}
func (m *StreamInputResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamInputResp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamInputResp proto.InternalMessageInfo

type StreamTestReq struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTestReq) Reset()         { *m = StreamTestReq{} }
func (m *StreamTestReq) String() string { return proto.CompactTextString(m) }
func (*StreamTestReq) ProtoMessage()    {}
func (*StreamTestReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *StreamTestReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTestReq.Unmarshal(m, b)
}
func (m *StreamTestReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTestReq.Marshal(b, m, deterministic)
}
func (m *StreamTestReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTestReq.Merge(m, src)
}
func (m *StreamTestReq) XXX_Size() int {
	return xxx_messageInfo_StreamTestReq.Size(m)
}
func (m *StreamTestReq) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTestReq.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTestReq proto.InternalMessageInfo

type StreamTestResp struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamTestResp) Reset()         { *m = StreamTestResp{} }
func (m *StreamTestResp) String() string { return proto.CompactTextString(m) }
func (*StreamTestResp) ProtoMessage()    {}
func (*StreamTestResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *StreamTestResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamTestResp.Unmarshal(m, b)
}
func (m *StreamTestResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamTestResp.Marshal(b, m, deterministic)
}
func (m *StreamTestResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamTestResp.Merge(m, src)
}
func (m *StreamTestResp) XXX_Size() int {
	return xxx_messageInfo_StreamTestResp.Size(m)
}
func (m *StreamTestResp) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamTestResp.DiscardUnknown(m)
}

var xxx_messageInfo_StreamTestResp proto.InternalMessageInfo

func (m *StreamTestResp) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*UserReq)(nil), "pb.UserReq")
	proto.RegisterType((*UserResp)(nil), "pb.UserResp")
	proto.RegisterType((*StreamInputReq)(nil), "pb.StreamInputReq")
	proto.RegisterType((*StreamInputResp)(nil), "pb.StreamInputResp")
	proto.RegisterType((*StreamTestReq)(nil), "pb.StreamTestReq")
	proto.RegisterType((*StreamTestResp)(nil), "pb.StreamTestResp")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x2d, 0x4e, 0x2d,
	0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xe2, 0xe4, 0x62, 0x0f, 0x2d,
	0x4e, 0x2d, 0x0a, 0x4a, 0x2d, 0x54, 0xe2, 0xe2, 0xe2, 0x80, 0x30, 0x8b, 0x0b, 0x94, 0xd4, 0xb8,
	0xf8, 0x82, 0x4b, 0x8a, 0x52, 0x13, 0x73, 0x3d, 0xf3, 0x0a, 0x4a, 0x4b, 0x82, 0x52, 0x0b, 0x85,
	0x44, 0xb8, 0x58, 0x33, 0x41, 0x6c, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x49,
	0x90, 0x8b, 0x1f, 0x45, 0x5d, 0x71, 0x81, 0x12, 0x3f, 0x17, 0x2f, 0x44, 0x28, 0x24, 0xb5, 0x18,
	0xa4, 0x53, 0x49, 0x0b, 0x66, 0x16, 0x44, 0xa0, 0xb8, 0x40, 0x48, 0x82, 0x8b, 0x3d, 0x37, 0xb5,
	0xb8, 0x38, 0x31, 0x3d, 0x15, 0x6a, 0x1a, 0x8c, 0x6b, 0xb4, 0x82, 0x91, 0x8b, 0x1b, 0xe4, 0x88,
	0xe0, 0xd4, 0xa2, 0xb2, 0xcc, 0xe4, 0x54, 0x21, 0x4d, 0x2e, 0x1e, 0x10, 0xd7, 0x39, 0x31, 0x27,
	0x07, 0xa4, 0x5b, 0x88, 0x5b, 0xaf, 0x20, 0x49, 0x0f, 0xea, 0x60, 0x29, 0x1e, 0x04, 0xa7, 0xb8,
	0x40, 0xc8, 0x8c, 0x8b, 0x1b, 0xc9, 0x29, 0x42, 0x42, 0x20, 0x49, 0x54, 0x3f, 0x48, 0x09, 0x63,
	0x88, 0x81, 0xf5, 0x71, 0x21, 0x9c, 0x27, 0x24, 0x88, 0x50, 0x02, 0x75, 0x3f, 0x56, 0x5d, 0x06,
	0x8c, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xd6, 0x05, 0x49, 0x49, 0x6c, 0xe0, 0xc0, 0x34, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x28, 0x95, 0x04, 0xf5, 0x5a, 0x01, 0x00, 0x00,
}
